### ISSUE TITLE
doesn't seem to identify artists properly

### ISSUE THREAD

**Issue by ghost** [schnatterer/nusic#29]
I let it do a scan on my device, but it only found 3 artists. I must have +100 artists on my music folders. Not sure why it can't find them all - I know musicbrainz and I use it on my PC so I wonder what's going on.

**Comment by schnatterer** [comment]
@cyberhardt what do you mean by "3 artists"? Does it only show 3 releases of distinct artists? 
Have you tried pushing the ![Screenshot_20230918-210216~2.png](https://github.com/schnatterer/nusic/assets/1824962/1c24170e-a37f-4726-8228-42d311e5cf8b) button? The dialog shows a progress bar containing the number of artists, as these are queried one by one. What does this number show? 0/3?

nusic queries the artists from your Android system and feeds them one by one into musicbrainz verbatim. 

If you display artists in your stock "music" app, how many does it show?

In developer settings you can Enable "show errors during refresh". This will also tell you how many artists failed during refresh.

Especially if you have a lot of artists the process takes a long time (due to musicbrainz' rate limit) and therefore is prone to errors like connection losses.

It runs once per day so it's eventually consistent.

**Comment by ghost** [comment]
oh... wait... I get it now. it isn't supposed to show a list of all the artists and their new releases, but only those that have new stuff.
